Array Revision

In [1]:
import numpy as np

In [2]:
l  = [1,83,39]

In [3]:
print(type(l))

<class 'list'>


In [4]:
arr_l = np.array(l)

In [5]:
print(type(arr_l))

<class 'numpy.ndarray'>


In [6]:
arr = np.arange(0, 101, 5)
print(arr)

[  0   5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85
  90  95 100]


In [7]:
print(type(arr))

<class 'numpy.ndarray'>


In [8]:
zero = np.zeros((5,5))
zero

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
np.random.seed(101)
np.random.randint(1,100,10)

array([96, 12, 82, 71, 64, 88, 76, 10, 78, 41])

In [20]:
arr.argmax()

20

In [23]:
arr.reshape(7,3)

array([[  0,   5,  10],
       [ 15,  20,  25],
       [ 30,  35,  40],
       [ 45,  50,  55],
       [ 60,  65,  70],
       [ 75,  80,  85],
       [ 90,  95, 100]])

In [43]:
mat = np.arange(0,100).reshape(10,10)

In [44]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [45]:
mat[0:4,0:4]

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33]])